on:
  push:
    tags:
      - v*
jobs:
  release:
    if: github.ref_name == 'master'
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.1
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v5.1.0
        with:
          dotnet-version: 10.0.x
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test --no-restore --verbosity normal
      - name: Publish
        run: dotnet publish --configuration Release --self-contained true --no-restore --output dist /p:UseAppHost=true
      - name: Zip release
        run: zip -r dist.zip dist
      - name: Create Release
        run: gh release create ${GITHUB_REF#refs/*/} -t ${GITHUB_REF#refs/*/} dist.zip
